@php
    $logoSrc =
        isset($logoBase64) && $logoBase64 ? 'data:image/png;base64,' . $logoBase64 : asset('assets/images/OIP.png');

    $logoSrc =
        isset($logoBase64) && $logoBase64 ? 'data:image/png;base64,' . $logoBase64 : asset('assets/images/OIP.png');

    $formatReportDate = function ($feedback): string {
        $date = $feedback->visit_date ?? $feedback->created_at;

        return $date?->format('M. j, Y') ?? '—';
    };

    $visitorDisplayName = function ($feedback): string {
        return filled($feedback->name) ? $feedback->name : 'Anonymous Visitor';
    };
@endphp

<article class="report-document {{ $documentClass ?? '' }}">
    <header class="report-document__header">
        <div class="report-document__logo">
            <img src="{{ $logoSrc }}" alt="Cagayan Museum logo" width="64" height="64">
        </div>

        <div class="report-document__titles">
            <h1 class="report-document__museum">CAGAYAN MUSEUM</h1>
            <p class="report-document__report-title">Visitor Feedback Report</p>
            <p class="report-document__report-subtitle">Official Period Summary</p>
        </div>

        <div class="report-document__logo report-document__logo--right">
            <img src="{{ $logoSrc }}" alt="Cagayan Museum logo" width="64" height="64">
        </div>
    </header>

    {{-- Report metadata --}}
    <section class="report-document__meta" aria-label="Report information">
        <h2 class="report-document__section-title">Report Information</h2>

        <dl class="report-document__fields">
            <div class="report-document__field">
                <dt>Report Period</dt>
                <dd>{{ $report['periodLabel'] }}</dd>
            </div>
            <div class="report-document__field">
                <dt>Date Generated</dt>
                <dd>{{ $report['generatedOn']->format('F j, Y') }}</dd>
            </div>
            <div class="report-document__field">
                <dt>Generated By</dt>
                <dd>{{ $report['generatedBy'] }}</dd>
            </div>
        </dl>
    </section>

    <section class="report-document__section">
        <h2 class="report-document__section-title">Visitor Information</h2>

        @if ($report['visitors']->isEmpty())
            <p class="report-document__empty">No visitor records for this period.</p>
        @else
            <table class="report-document__data-table">
                <thead>
                    <tr>
                        <th scope="col" class="report-document__col-no">No.</th>
                        <th scope="col">Visitor Name</th>
                        <th scope="col">Province / Place</th>
                        <th scope="col">Age Range</th>
                        <th scope="col">Date</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($report['visitors'] as $index => $visitor)
                        <tr>
                            <td class="report-document__col-no">{{ $index + 1 }}</td>
                            <td>{{ $visitorDisplayName($visitor) }}</td>
                            <td>{{ $visitor->residenceLabel() ?? 'N/A' }}</td>
                            <td>{{ $visitor->ageRangeLabel() ?? 'N/A' }}</td>
                            <td>{{ $formatReportDate($visitor) }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endif
    </section>

    <section class="report-document__section report-document__section--break">
        <h2 class="report-document__section-title">Feedback Details</h2>

        @if ($report['feedbacks']->isEmpty())
            <p class="report-document__empty">No feedback submissions recorded for this period.</p>
        @else
            <ol class="report-document__feedback-list">
                @foreach ($report['feedbacks'] as $index => $feedback)
                    <li class="report-document__feedback-item">
                        <div class="report-document__feedback-meta">
                            <span class="report-document__feedback-no">{{ $index + 1 }}.</span>
                            <span class="report-document__feedback-date">{{ $formatReportDate($feedback) }}</span>
                            <span class="report-document__feedback-rating">
                                Rating:
                                @if ($feedback->experienceScore())
                                    {{ $feedback->experienceScore() }} / 5
                                @else
                                    N/A
                                @endif
                            </span>
                        </div>
                        <p class="report-document__feedback-text">
                            {{ filled($feedback->comments) ? $feedback->comments : '—' }}</p>
                    </li>
                @endforeach
            </ol>
        @endif
    </section>

    <footer class="report-document__footer">
        <p class="report-document__footer-line">Cagayan Museum</p>
        <p class="report-document__footer-line">Visitor Feedback System</p>
        <p class="report-document__footer-meta">
            Generated by: {{ $report['generatedBy'] }}<br>
            Date Generated: {{ $report['generatedOn']->format('F j, Y') }}
        </p>
    </footer>
</article>
